[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = {version="0.29.0", features=["bundled"]}
sqlite-vss = { path = "../../bindings/rust", features=["download-libs"] }

[[bin]]
name="demo"
path="demo.rs"
