name: "test build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-ubuntu:
    name: Testing ubuntu-18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - working-directory: vendor
        run: ./get_sqlite.sh
      - working-directory: vendor/sqlite
        run: ./configure && make
      - run: sudo apt-get install -y cmake
      - run: cmake -B build; make -C build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/vss0.so
  test-macos:
    name: Testing macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - working-directory: vendor
        run: ./get_sqlite.sh
      - working-directory: vendor/sqlite
        run: ./configure && make
      - run: brew install cmake
      - run: cmake -B build; make -C build
        env:
          # https://stackoverflow.com/questions/48825416/missing-openmp-c-flags-openmp-c-lib-names
          CC: /usr/local/opt/llvm/bin/clang
          CXX: /usr/local/opt/llvm/bin/clang++
          LDFLAGS: "-L/usr/local/opt/llvm/lib"
          CPPFLAGS: "-I/usr/local/opt/llvm/include"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: build/vss0.dylib
